name: learningdart
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3  
  http: ^0.13.4  
  animations: ^2.0.2
  lottie: ^2.0.0
  file_picker: ^8.3.1
  video_player: ^2.7.0
  logger: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        default_package: file_picker
      ios:
        default_package: file_picker

  assets:
    - assets/upload.json
    - assets/analysis.json
    - assets/loading.json
    - assets/videos/logo.mp4

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
